export const dataFake = [
{
    id:2,
        "flag": "../assets/flags/4x3/za.svg",
        "alt": "",
        "CountryName": "",
        "lema": "",
        "capital": "",
        "idioma": "",
        "continente": "",
        "posicaoPolitica": "Presidente",
        "presidente": "",
        "posicaoPolitica2": "Vice-Presidente",
        "vicePresidente": "",
        "populacao": "",
        "independencia": "",
        "proclamacaoIndependencia": "",
        "divisaoTerritorio": "Quantidade de províncias:",
        "qtdEstados": "",
        "territorio": "",
        "maiorEstadoTrTitle": "Maior província em territorio:",
        "maiorEstadoTr": "",
        "menorEstadoTrTitle": "Menor província em territorio:",
        "menorEstadoTr": "",
        "maiorEstadoPlTitle": "Maior província em população:",
        "maiorEstadoPl": "",
        "menorEstadoPlTitle": "Menor província em população:",
        "menorEstadoPl": "",
        "maiorCidadePl": "",
        "maiorCidadeTr": "",
        "fronteiras": "",
        "imgMaravilhaDoMundo": "",
        "altMaravilhaDoMundo": "",
        "maioresPaises": "",
        "curiosidade":"Uma curiosidade interessante sobre a África do Sul é que o país tem três capitais. Esta abordagem única é parte da estrutura governamental do país, que é baseada na divisão de funções entre o legislativo, executivo e judiciário.",
        // "hinoNacional": '<iframe width="380" height="315" src="https://www.youtube.com/embed/SyyOahYXhUQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
        },
]
